version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - pms_network
    environment:
      MONGODB_URI: mongodb://localhost:27017/
      JWT_SECRET: Godfather
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - pms_network
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5000
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - pms_network
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

networks:
  pms_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local