name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: chandrabhan4122003
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: false

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: chandrabhan4122003/pms-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: chandrabhan4122003/pms-frontend:latest

      - name: Set up Docker Compose
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps